### ISSUE TITLE
Inflight QOS 2 messages are dropped after reconnecting

### ISSUE THREAD

**Issue by elvoe** [erlio/vernemq#496]
### Environment

VerneMQ Version: 1.1.1 binary package
(only non-default setting is max_inflight_messages = 500)
OS: Ubuntu 16.04 x64

MQTT client: Eclipse Paho Java
Paho max inflight set to 200.
Clean session is false
Ping from client to broker: 160 ms

### Expected behavior

If the connection gets interupted while publishing messages using QOS 2, inflight messages should be delivered after reconnecting.

### Actual behaviour

I am trying to publish messages as fast as possible. I have one publisher and one subscriber using QOS 2.
I interupt the connection (I simply pull the network-cable) after the publisher have received a PUBCOMP for 333 messages.

200 messages are still inflight and I wait 60+ seconds for the publisher to detect the dead connection.
I reestablish the connection and expect the remaining 200 messages to be delivered after reconnecting, but the subscriber only receives 163 messages.

The VMQ metrics shows that 200 PUBREL where received after reconnecting, but VerneMQ only responds with 163 PUBCOMP (according to VMQ metrics). However, the publisher DO RECEIVE 200 NON-DUPLICATE PUBCOMP.

I have tried using the Mosquitto broker instead without any problems.

**After interupting connection:**
Publisher inflight (according to client): 200
Publisher PUBCOMP received (according to client): 333
Subscriber received (according to subscriber-client): 353

```
counter.mqtt_publish_received = 386
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 353
counter.mqtt_pubrel_received = 353
counter.mqtt_pubcomp_received = 353
counter.mqtt_publish_sent = 353
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 386
counter.mqtt_pubrel_sent = 353
counter.mqtt_pubcomp_sent = 353
counter.queue_setup = 0
counter.queue_teardown = 0
counter.queue_message_drop = 0
counter.queue_message_unhandled = 0
counter.queue_message_in = 353
counter.queue_message_out = 353
```

**After reconnecting and waiting for inflight to clear:**
Publisher inflight (according to client): 0
Publisher PUBCOMP received (according to client): 533
VerneMQ PUBCOMP sent: 516 **(it should be 533 as that is what the publisher received)**
Subscriber received (according to subscriber-client): 516 **(where is the remaining 17?)**

```
counter.mqtt_publish_received = 549
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 516
counter.mqtt_pubrel_received = 553
counter.mqtt_pubcomp_received = 516
counter.mqtt_publish_sent = 516
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 747
counter.mqtt_pubrel_sent = 516
counter.mqtt_pubcomp_sent = 516
counter.queue_setup = 0
counter.queue_teardown = 0
counter.queue_message_drop = 0
counter.queue_message_unhandled = 0
counter.queue_message_in = 516
counter.queue_message_out = 516
```

**Comment by ioolkos** [comment]
@JonathanElvoe thanks for reporting! is this reproducable? with the same numbers?

so we have a case here where the numbers don't add up or don't agree with the receiving clients statistics.
@dergraf @larshesel can you make sense of this? (hypothese for missing 16 messages)

**Comment by dergraf** [comment]
@JonathanElvoe I think I've spotted the error. We'll rollout a fix within the next bugfix release.

@larshesel , @ioolkos in    https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_ranch.erl#L196 we should actually call into the `vmq_mqtt_fsm` and tell to properly terminate. This is a mistake, sorry that it was forgotten, thank you @JonathanElvoe for reporting!

**Comment by JonathanElvoe** [comment]
Hi there, glad I could help you spot an error. Unfortunately, I just tried building from the fixed source, and I can still reproduce the problem. I have attached metrics from another run (using the new build). This time 15 missing messages.
[vmq_metrics.txt](https://github.com/erlio/vernemq/files/1268297/vmq_metrics.txt)

**Comment by dergraf** [comment]
ok, without going into details, maybe this is what happens:

I guess you might run into the following situation:
For QoS2 VerneMQ currently throws away the PUBREL state (e.g. the server session is waiting for a PUBREL sent from the client) if the client disconnects. Therefore if a client sends the outstanding PUBRELs right after reconnecting we won't find a matching message.

I guess this violates the spec in [MQTT-4.4.0-1]. We should fix this.

**Comment by larshesel** [comment]
@dergraf isn't is just the ordering of the clauses that's the problem. Moving the clause on line 776 (which actually handles the pubrel frames) up before the one ignoring all qos2 msgs should ensure we handle the pubrel frame?

The logic seems to be broken as the first clause filtering out qos2 shadows the pubrel clause as that only happens in a qos2 setting?

**Comment by larshesel** [comment]
ping @dergraf

**Comment by francois-travais** [comment]
This is a rather bad bug, it means QoS 2 doesn't really work and messages can be lost very easily ! Are you guys working on it ? @dergraf @larshesel

**Comment by larshesel** [comment]
Hi, we'd kind of lost this from our radar - I'll see if I can work on this one of the following days.

**Comment by larshesel** [comment]
Thinking a bit more about this, I think the issue of the messages not arriving at the client should be solved as we've changed when the message is actually routed to the subscriber. In the MQTT spec for a qos2 flow one can store either forward the message when receiving a PUBLISH packet or store it and forward it when the PUBREL arrives. We used to forward the message when the PUBREL arrives, now we do it immediately when the PUBLISH arrives.

This was fixed in 1.5.0. I'll see if I can't write a test case for this so we have this covered in the future, but it would be great if @elvoe could confirm.

**Comment by elvoe** [comment]
Hi, I just tried to spin up my old scenario with VerneMQ 1.1.1 and I could still reproduce the issue. I then upgraded to 1.6.0, ran the scenario again, and just like that, no more dropped messages.
Only thing I noticed was some duplicate messages if subscriber was using QoS 0, but that is expected based on your chosen implementation and still within the MQTT specification. Finally, I changed the subscriber to QoS 2, and then the number of messages published and received added up perfectly. Well done VerneMQ team!
